import express from "express";
import cors from "cors";
import userRoutes from "./routes/user.routes";
import notFoundMw from "./middlewares/not-found.mw";
import errorMw from "./middlewares/error.mw";
import path from "path";
const app = express();
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(cors());
app.use("/uploads", express.static(path.join(__dirname, "../", "uploads")));
app.use("/api/v1/users", userRoutes);
app.use(notFoundMw);
app.use(errorMw);
export default app;
